name: Run Tests and Publish Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Automation Suite
        uses: actions/checkout@v4

      - name: Checkout E-commerce Site
        uses: actions/checkout@v4
        with:
          repository: dewanganbasant21/my-ecom-store
          path: ecommerce-site

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install & Start E-commerce Server
        run: |
          cd ecommerce-site
          npm install
          npm run dev &
          npx --yes wait-on http://localhost:5173

      - name: Install Automation Suite Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Automation Tests
        run: npm run test:playwright
        env:
          BASE_URL: http://localhost:5173/
          BROWSER_TYPE: playwright
          HEADLESS: "true"
        continue-on-error: true

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/main_report
          publish_branch: gh-pages
